version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
      args:
        - GITHUB_AT=$GITHUB_AT
    container_name: yii2-morrisjs
    volumes:
      - .:/var/www/yii2-morrisjs
    links:
      - nginx
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./Docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/yii2-morrisjs
      - ./Docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80

